[package]
name = "calc-rs"
version = "2.0.0"
edition = "2021"
authors = ["arshergon", "arshergon@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clearscreen = "2.0.0"
colored = "3.0.0"
rustyline = "17.0.2"
